"""Disable relationships temporarily

Revision ID: 31ccce9a35f3
Revises: 7cc496fd4fb2
Create Date: 2025-04-17 17:55:09.230401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ccce9a35f3'
down_revision: Union[str, None] = '7cc496fd4fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
