"""add created_at

Revision ID: 97faf91733d1
Revises: 
Create Date: 2025-04-14 15:45:28.771084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97faf91733d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'created_at')
    # ### end Alembic commands ###
